// @xihan-ui/headless —— 无头组件（anatomy + machine + connect，无样式）。

export { accordionAnatomy, accordionKeyboard, accordionMachine, accordionMeta, connectAccordion } from './accordion'
export type { AccordionApi, AccordionItemProps, AccordionSchema, AccordionValueChangeDetails } from './accordion'
export { avatarAnatomy, avatarKeyboard, avatarMachine, avatarMeta, connectAvatar } from './avatar'
export type { AvatarApi, AvatarSchema, AvatarStatus, AvatarStatusChangeDetails } from './avatar'
export { badgeAnatomy, badgeKeyboard, badgeMeta, connectBadge } from './badge'
export type { BadgeApi, BadgeProps } from './badge'
export { breadcrumbAnatomy, breadcrumbKeyboard, breadcrumbMeta, connectBreadcrumb } from './breadcrumb'
export type { BreadcrumbApi, BreadcrumbLinkProps, BreadcrumbProps, BreadcrumbTranslations } from './breadcrumb'
export { buttonAnatomy, buttonKeyboard, buttonMeta, connectButton } from './button'

export type { ButtonApi, ButtonProps } from './button'
export { checkboxAnatomy, checkboxKeyboard, checkboxMachine, checkboxMeta, connectCheckbox } from './checkbox'
export type { CheckboxApi, CheckboxCheckedChangeDetails, CheckboxSchema } from './checkbox'
export { checkboxGroupAnatomy, checkboxGroupKeyboard, checkboxGroupMachine, checkboxGroupMeta, connectCheckboxGroup, resolveCheckedState, toggleAllValues, toggleItemValue } from './checkbox-group'
export type { CheckboxGroupApi, CheckboxGroupCheckedState, CheckboxGroupItemProps, CheckboxGroupSchema, CheckboxGroupValueChangeDetails } from './checkbox-group'
export { CLIPBOARD_TIMEOUT, clipboardAnatomy, clipboardKeyboard, clipboardMachine, clipboardMeta, connectClipboard, resolveClipboardTimeout, writeToClipboard } from './clipboard'
export type { ClipboardApi, ClipboardCopyErrorDetails, ClipboardIndicatorProps, ClipboardSchema, ClipboardStatus, ClipboardStatusChangeDetails } from './clipboard'
export { collapsibleAnatomy, collapsibleKeyboard, collapsibleMachine, collapsibleMeta, connectCollapsible } from './collapsible'
export type { CollapsibleApi, CollapsibleOpenChangeDetails, CollapsibleSchema } from './collapsible'
export { COMBOBOX_DEFAULT_PLACEMENT, comboboxAnatomy, comboboxItemQuery, comboboxItemText, comboboxKeyboard, comboboxMachine, comboboxMeta, connectCombobox } from './combobox'
export type { ComboboxApi, ComboboxFocusIntent, ComboboxInputBehavior, ComboboxInputValueChangeDetails, ComboboxItemGroupProps, ComboboxItemProps, ComboboxOpenChangeDetails, ComboboxRefs, ComboboxSchema, ComboboxValueChangeDetails } from './combobox'
export { connectContextMenu, CONTEXT_MENU_DEFAULT_OFFSET, CONTEXT_MENU_DEFAULT_PLACEMENT, CONTEXT_MENU_LONG_PRESS_DELAY, CONTEXT_MENU_MOVE_TOLERANCE, contextMenuAnatomy, contextMenuItemQuery, contextMenuItemText, contextMenuKeyboard, contextMenuMachine, contextMenuMeta } from './context-menu'
export type { ContextMenuApi, ContextMenuFocusIntent, ContextMenuGroupProps, ContextMenuItemProps, ContextMenuOpenChangeDetails, ContextMenuPoint, ContextMenuRefs, ContextMenuSchema, ContextMenuSelectDetails } from './context-menu'
export { connectDialog, dialogAnatomy, dialogKeyboard, dialogMachine, dialogMeta } from './dialog'

export type { DialogApi, DialogOpenChangeDetails, DialogRefs, DialogSchema, DialogTranslations } from './dialog'
export { connectDrawer, DRAWER_DEFAULT_SIDE, drawerAnatomy, drawerKeyboard, drawerMachine, drawerMeta } from './drawer'
export type { DrawerApi, DrawerOpenChangeDetails, DrawerRefs, DrawerSchema, DrawerSide, DrawerTranslations } from './drawer'
export { clampEditableValue, connectEditable, EDITABLE_DEFAULT_ACTIVATION_MODE, EDITABLE_DEFAULT_SUBMIT_MODE, editableAnatomy, editableInputSize, editableKeyboard, editableMachine, editableMeta, submitsOnEnter, submitsOnLeave } from './editable'
export type { EditableActivationMode, EditableApi, EditableEditChangeDetails, EditableRefs, EditableSchema, EditableSubmitMode, EditableValueChangeDetails, EditableValueCommitDetails, EditableValueRevertDetails } from './editable'
export { connectField, fieldAnatomy, fieldKeyboard, fieldMeta } from './field'
export type { FieldApi, FieldProps } from './field'
export { acceptAttr, acceptsFile, connectFileUpload, FILE_UPLOAD_MAX_FILES, fileUploadAnatomy, fileUploadHiddenInputId, fileUploadKeyboard, fileUploadMachine, fileUploadMeta, formatFileSize, normalizeAccept, normalizeMaxFiles, sameFiles, validateFiles } from './file-upload'
export type { FileRejectReason, FileUploadApi, FileUploadFileAcceptDetails, FileUploadFileRejectDetails, FileUploadFilesChangeDetails, FileUploadItemProps, FileUploadRejection, FileUploadSchema, FileUploadTranslations, FileUploadValidationResult, FileValidationOptions } from './file-upload'
export { connectHoverCard, hoverCardAnatomy, hoverCardKeyboard, hoverCardMachine, hoverCardMeta } from './hover-card'
export type { HoverCardApi, HoverCardOpenChangeDetails, HoverCardRefs, HoverCardSchema } from './hover-card'
export { connectImage, imageAnatomy, imageKeyboard, imageMachine, imageMeta, resolveFallbackDelay } from './image'
export type { ImageApi, ImageSchema, ImageStatus, ImageStatusChangeDetails } from './image'
export { connectListbox, listboxAnatomy, listboxItemQuery, listboxItemText, listboxKeyboard, listboxMachine, listboxMeta, listboxSelectionMode } from './listbox'
export type { ListboxApi, ListboxFocusModel, ListboxItemGroupProps, ListboxItemProps, ListboxRefs, ListboxSchema, ListboxSelectionMode, ListboxValueChangeDetails } from './listbox'
export { connectMenu, menuAnatomy, menuKeyboard, menuMachine, menuMeta } from './menu'
export type { MenuApi, MenuFocusIntent, MenuItemProps, MenuOpenChangeDetails, MenuRefs, MenuSchema, MenuSelectDetails } from './menu'
export { connectNumberField, NUMBER_FIELD_CHANGE_DELAY, NUMBER_FIELD_CHANGE_INTERVAL, NUMBER_FIELD_STEP, numberFieldAnatomy, numberFieldKeyboard, numberFieldMachine, numberFieldMeta } from './number-field'
export type { NumberFieldApi, NumberFieldSchema, NumberFieldValueChangeDetails } from './number-field'
export { buildPageSequence, clampPage, connectPagination, normalizeCount, normalizePageSize, pageRangeOf, PAGINATION_PAGE_SIZE, PAGINATION_SIBLING_COUNT, paginationAnatomy, paginationKeyboard, paginationMachine, paginationMeta, totalPagesOf } from './pagination'
export type { PaginationApi, PaginationEntryRange, PaginationItemProps, PaginationPage, PaginationPageChangeDetails, PaginationSchema, PaginationTranslations } from './pagination'
export { connectPinInput, isPinComplete, padPinValue, PIN_INPUT_LENGTH, pinInputAnatomy, pinInputKeyboard, pinInputMachine, pinInputMeta, pinLength, samePinValue, sanitizePin } from './pin-input'
export type { PinInputApi, PinInputInputProps, PinInputSchema, PinInputType, PinInputValueChangeDetails } from './pin-input'
export { connectPopover, popoverAnatomy, popoverKeyboard, popoverMachine, popoverMeta } from './popover'
export type { PopoverApi, PopoverOpenChangeDetails, PopoverRefs, PopoverSchema, PopoverTranslations } from './popover'
export { connectProgress, progressAnatomy, progressKeyboard, progressMeta } from './progress'
export type { ProgressApi, ProgressProps } from './progress'
export { connectRadioGroup, radioGroupAnatomy, radioGroupKeyboard, radioGroupMachine, radioGroupMeta } from './radio-group'
export type { RadioGroupApi, RadioGroupItemProps, RadioGroupSchema, RadioGroupValueChangeDetails } from './radio-group'
export { clampRating, connectRating, RATING_COUNT, ratingAnatomy, ratingIntentFromKey, ratingKeyboard, ratingMachine, ratingMax, ratingMeta, ratingStep, ratingValueAtPointer, stepRating } from './rating'
export type { RatingApi, RatingHoverChangeDetails, RatingItemProps, RatingItemState, RatingKeyEventLike, RatingKeyIntent, RatingSchema, RatingValueChangeDetails } from './rating'
export { connectSelect, SELECT_DEFAULT_PLACEMENT, selectAnatomy, selectItemQuery, selectItemText, selectKeyboard, selectMachine, selectMeta } from './select'
export type { SelectApi, SelectFocusIntent, SelectItemProps, SelectOpenChangeDetails, SelectRefs, SelectSchema, SelectValueChangeDetails } from './select'
export { connectSeparator, separatorAnatomy, separatorKeyboard, separatorMeta } from './separator'
export type { SeparatorApi, SeparatorProps } from './separator'
export { closestThumb, connectSlider, percentToValue, pointToValue, rangeExtent, setThumbValue, SLIDER_MAX, SLIDER_MIN, SLIDER_STEP, sliderAnatomy, sliderKeyboard, sliderMachine, sliderMeta, snapToStep, thumbBounds, valueToPercent } from './slider'
export type { AxisOptions, SliderApi, SliderPoint, SliderSchema, SliderThumbState, SliderValueChangeDetails, SliderValueChangeEndDetails, SliderValueTextDetails, TrackRect } from './slider'
export type { ComponentMeta, KeyboardRow, KeyboardTable } from './spec'
export { clampStep, connectSteps, normalizeStepCount, stepsAnatomy, stepsKeyboard, stepsMachine, stepsMeta } from './steps'
export type { StepsApi, StepsItemProps, StepsItemState, StepsSchema, StepsStepChangeDetails, StepStatus } from './steps'
export { connectSwitch, switchAnatomy, switchKeyboard, switchMachine, switchMeta } from './switch'
export type { SwitchApi, SwitchCheckedChangeDetails, SwitchSchema } from './switch'
export { connectTabs, tabsAnatomy, tabsKeyboard, tabsMachine, tabsMeta } from './tabs'
export type { TabsActivationMode, TabsApi, TabsContentProps, TabsSchema, TabsTriggerProps, TabsValueChangeDetails } from './tabs'
export { appendTags, connectTagsInput, isAtMax, isOverflow, normalizeTag, normalizeTags, sameTags, splitTags, TAGS_INPUT_DELIMITER, tagsDelimiter, tagsInputAnatomy, tagsInputEditInputId, tagsInputKeyboard, tagsInputMachine, tagsInputMeta } from './tags-input'
export type { TagsAppendOptions, TagsAppendResult, TagsInputApi, TagsInputBlurBehavior, TagsInputInputValueChangeDetails, TagsInputItemProps, TagsInputSchema, TagsInputTranslations, TagsInputValueChangeDetails } from './tags-input'
export { clampToMaxLength, connectTextField, isAtLimit, textFieldAnatomy, textFieldKeyboard, textFieldMachine, textFieldMeta } from './text-field'
export type { TextFieldApi, TextFieldSchema, TextFieldValueChangeDetails } from './text-field'
export { connectToast, resolveToastDuration, resolveToastId, TOAST_DURATION, TOAST_REMOVE_DELAY, toastAnatomy, toastKeyboard, toastMachine, toastMeta } from './toast'
export type { ToastActionDetails, ToastApi, ToastPauseSource, ToastSchema, ToastStatus, ToastStatusChangeDetails, ToastTranslations, ToastType } from './toast'
export { connectToaster, TOAST_PLACEMENTS, TOASTER_GAP, TOASTER_PLACEMENT, toasterAnatomy, toasterKeyboard, toasterMachine, toasterMeta, toastPlacementOf, visibleToasts } from './toaster'
export type { ResolvedToast, ToasterApi, ToasterGroupProps, ToasterSchema, ToasterToastsChangeDetails, ToasterTranslations, ToastOptions, ToastPlacement, ToastRecord } from './toaster'
export { connectToggle, toggleAnatomy, toggleKeyboard, toggleMachine, toggleMeta } from './toggle'
export type { ToggleApi, TogglePressedChangeDetails, ToggleSchema } from './toggle'
export { connectToggleGroup, normalizeToggleGroupValue, sameToggleGroupValue, toggleGroupAnatomy, toggleGroupKeyboard, toggleGroupMachine, toggleGroupMeta, toToggleGroupChangeValue } from './toggle-group'
export type { ToggleGroupApi, ToggleGroupItemProps, ToggleGroupSchema, ToggleGroupValue, ToggleGroupValueChangeDetails } from './toggle-group'
export { connectToolbar, toolbarAnatomy, toolbarItemQuery, toolbarKeyboard, toolbarMachine, toolbarMeta } from './toolbar'
export type { ToolbarApi, ToolbarItemProps, ToolbarSchema } from './toolbar'
export { connectTooltip, tooltipAnatomy, tooltipKeyboard, tooltipMachine, tooltipMeta } from './tooltip'
export type { TooltipApi, TooltipOpenChangeDetails, TooltipRefs, TooltipSchema } from './tooltip'
export { connectTree, flattenTree, indexTree, treeAnatomy, treeBranchQuery, treeItemQuery, treeKeyboard, treeMachine, treeMeta, treeSelectionMode } from './tree'
export type { TreeApi, TreeExpandedChangeDetails, TreeFocusModel, TreeNode, TreeNodeMeta, TreeNodeProps, TreeRefs, TreeSchema, TreeSelectionChangeDetails, TreeSelectionMode, TreeVisibleNode } from './tree'
export type { HeadlessComponent, NormalizeProps, PropTypes } from './types'
