// @vitest-environment jsdom
import { accordionSuite, affixSuite, alertSuite, anchorSuite, avatarGroupSuite, avatarSuite, backTopSuite, badgeSuite, breadcrumbSuite, buttonGroupSuite, buttonSuite, calendarSuite, cardSuite, carouselSuite, cascaderSuite, checkboxGroupSuite, checkboxSuite, clipboardSuite, codeBlockSuite, codeViewSuite, collapsibleSuite, colorPickerSuite, comboboxSuite, composerSuite, contextMenuSuite, countdownSuite, dateFieldSuite, datePickerSuite, descriptionsSuite, dialogSuite, downloadTriggerSuite, drawerSuite, dynamicInputSuite, editableSuite, ellipsisSuite, emptyStateSuite, fieldsetSuite, fieldSuite, fileUploadSuite, flexSuite, floatButtonSuite, floatingPanelSuite, formSuite, gradientTextSuite, gridSuite, heatmapSuite, highlightSuite, hotkeysSuite, hoverCardSuite, iconSuite, iconWrapperSuite, imageCropperSuite, imageSuite, imageViewerSuite, infiniteScrollSuite, jsonViewerSuite, layoutSuite, listboxSuite, listSuite, loadingBarSuite, logSuite, markdownStreamSuite, marqueeSuite, masonrySuite, mentionSuite, menubarSuite, menuSuite, messageFeedSuite, navigationMenuSuite, notificationSuite, numberAnimationSuite, numberFieldSuite, pageHeaderSuite, paginationSuite, passwordInputSuite, pinInputSuite, popconfirmSuite, popoverSuite, popselectSuite, progressSuite, qrCodeSuite, radioGroupSuite, ratingSuite, resizableSuite, resultSuite, runConformance, scrollAreaSuite, scrollbarSuite, segmentedSuite, selectSuite, separatorSuite, sideNavSuite, signaturePadSuite, skeletonSuite, sliderSuite, sortableSuite, spaceSuite, spinnerSuite, splitterSuite, statisticSuite, stepsSuite, switchSuite, tableSuite, tabsSuite, tagsInputSuite, tagSuite, textFieldSuite, threadSuite, timeFieldSuite, timelineSuite, timePickerSuite, timerSuite, timeSuite, toastSuite, toggleGroupSuite, toggleSuite, toolbarSuite, tooltipSuite, tourSuite, transferSuite, treeSelectSuite, treeSuite, typographySuite, virtualizerSuite, watermarkSuite } from '@xihan-ui/testing'
import { afterEach, describe, it } from 'vitest'
import { createVueHarness } from './harness'

afterEach(() => {
  document.body.innerHTML = ''
})

// 键盘/焦点相关行需真机验证，jsdom 态不强制全覆盖（浏览器态转硬门禁）。
runConformance(
  createVueHarness(),
  [
    affixSuite,
    alertSuite,

    avatarGroupSuite,
    backTopSuite,
    buttonGroupSuite,
    countdownSuite,
    descriptionsSuite,
    dynamicInputSuite,
    ellipsisSuite,
    emptyStateSuite,

    flexSuite,
    floatButtonSuite,
    gradientTextSuite,
    gridSuite,
    highlightSuite,
    iconWrapperSuite,
    infiniteScrollSuite,
    layoutSuite,
    listSuite,
    logSuite,
    markdownStreamSuite,
    marqueeSuite,
    mentionSuite,
    numberAnimationSuite,
    pageHeaderSuite,
    popconfirmSuite,
    popselectSuite,
    qrCodeSuite,
    resizableSuite,
    resultSuite,
    skeletonSuite,

    spinnerSuite,

    accordionSuite,
    anchorSuite,
    avatarSuite,
    badgeSuite,
    breadcrumbSuite,
    buttonSuite,
    calendarSuite,
    cardSuite,
    carouselSuite,
    checkboxGroupSuite,
    checkboxSuite,
    clipboardSuite,
    codeBlockSuite,
    codeViewSuite,
    collapsibleSuite,
    comboboxSuite,
    composerSuite,
    contextMenuSuite,
    dateFieldSuite,
    datePickerSuite,
    dialogSuite,
    drawerSuite,
    editableSuite,
    fieldSuite,
    fileUploadSuite,
    hoverCardSuite,
    iconSuite,
    imageSuite,
    listboxSuite,
    menuSuite,
    navigationMenuSuite,
    notificationSuite,
    numberFieldSuite,
    paginationSuite,
    pinInputSuite,
    popoverSuite,
    progressSuite,
    radioGroupSuite,
    ratingSuite,
    scrollAreaSuite,
    scrollbarSuite,
    selectSuite,
    separatorSuite,
    sliderSuite,
    sortableSuite,
    splitterSuite,
    statisticSuite,
    stepsSuite,
    switchSuite,
    tabsSuite,
    tagsInputSuite,
    textFieldSuite,
    threadSuite,
    timeFieldSuite,
    timePickerSuite,
    timeSuite,
    timelineSuite,
    toastSuite,
    toggleGroupSuite,
    toggleSuite,
    toolbarSuite,
    tooltipSuite,
    cascaderSuite,
    colorPickerSuite,
    formSuite,
    loadingBarSuite,
    menubarSuite,
    messageFeedSuite,
    tableSuite,
    tourSuite,
    transferSuite,
    typographySuite,
    virtualizerSuite,
    treeSelectSuite,
    treeSuite,
    watermarkSuite,
    spaceSuite,
    tagSuite,
    segmentedSuite,
    masonrySuite,
    passwordInputSuite,
    fieldsetSuite,
    jsonViewerSuite,
    timerSuite,
    heatmapSuite,
    downloadTriggerSuite,
    hotkeysSuite,
    imageCropperSuite,
    signaturePadSuite,
    floatingPanelSuite,
    imageViewerSuite,
    sideNavSuite,
  ],
  { describe, it },
  {
    // 焦点环绕要真实的 Tab 焦点移动，jsdom 按 Tab 不移动焦点，这四行在这里演不出来。
    // 陷阱本身（trapped/loop 的装配）由 focus-scope 的单测覆盖，环绕效果待真机验证。
    keyboardCoverageExempt: {
      'dialog.kbd.tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'dialog.kbd.shift-tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'popover.kbd.tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'popover.kbd.shift-tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'drawer.kbd.tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'drawer.kbd.shift-tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'image-viewer.kbd.tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'image-viewer.kbd.shift-tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      // 输入法那两行不是"暂时演不出来"，是运行时根本给不出信号：
      // 合成 KeyboardEvent 的 isComposing 恒 false（且 keyCode 恒 0），
      // 换行则是浏览器的默认行为、组件刻意不接管，于是连个可断言的属性都没有。
      'composer.kbd.ime-enter': 'jsdom 与浏览器都无法合成真实 IME 组合态，isComposing 恒 false',
      'composer.kbd.shift-enter': '换行是浏览器默认行为，组件不接管也就无属性可断言',
    },
  },
)
