// @vitest-environment jsdom
import { accordionSuite, affixSuite, alertSuite, anchorSuite, approvalSuite, avatarGroupSuite, avatarSuite, backTopSuite, badgeSuite, breadcrumbSuite, buttonGroupSuite, buttonSuite, calendarSuite, cardSuite, carouselSuite, cascaderSuite, checkboxGroupSuite, checkboxSuite, clipboardSuite, codeViewSuite, collapsibleSuite, colorPickerSuite, comboboxSuite, contextMenuSuite, dateFieldSuite, datePickerSuite, descriptionsSuite, dialogSuite, diffViewSuite, downloadTriggerSuite, drawerSuite, editableSuite, emptyStateSuite, fieldArraySuite, fieldsetSuite, fieldSuite, fileUploadSuite, flexSuite, floatButtonSuite, floatingPanelSuite, formSuite, gradientTextSuite, gridSuite, heatmapSuite, highlightSuite, hotkeysSuite, hoverCardSuite, iconSuite, iconWrapperSuite, imageCropperSuite, imageSuite, imageViewerSuite, infiniteScrollSuite, jsonViewerSuite, layoutSuite, listboxSuite, listSuite, loadingBarSuite, logSuite, markdownStreamSuite, marqueeSuite, masonrySuite, mentionSuite, menubarSuite, menuSuite, messageFeedSuite, navigationMenuSuite, notificationSuite, numberAnimationSuite, numberFieldSuite, pageHeaderSuite, paginationSuite, passwordInputSuite, pinInputSuite, popconfirmSuite, popoverSuite, progressSuite, promptInputSuite, qrCodeSuite, questionFlowSuite, radioGroupSuite, ratingSuite, reasoningSuite, resizableSuite, runConformance, scrollAreaSuite, scrollbarSuite, segmentedSuite, selectSuite, separatorSuite, sideNavSuite, signaturePadSuite, skeletonSuite, sliderSuite, sortableSuite, spinnerSuite, splitterSuite, statisticSuite, stepsSuite, switchSuite, tableSuite, tabsSuite, tagsInputSuite, tagSuite, textFieldSuite, timeFieldSuite, timelineSuite, timePickerSuite, timerSuite, timestampSuite, toastSuite, toggleGroupSuite, toggleSuite, toolbarSuite, toolCallSuite, tooltipSuite, tourSuite, transferSuite, treeSelectSuite, treeSuite, truncateSuite, typographySuite, virtualizerSuite, watermarkSuite } from '@xihan-ui/testing'
import { afterEach, describe, it } from 'vitest'
import { createVueHarness } from './harness'

afterEach(() => {
  document.body.innerHTML = ''
})

// 键盘/焦点相关行需真机验证，jsdom 态不强制全覆盖（浏览器态转硬门禁）。
runConformance(
  createVueHarness(),
  [
    affixSuite,
    alertSuite,

    avatarGroupSuite,
    backTopSuite,
    buttonGroupSuite,
    descriptionsSuite,
    fieldArraySuite,
    truncateSuite,
    emptyStateSuite,

    flexSuite,
    floatButtonSuite,
    gradientTextSuite,
    gridSuite,
    highlightSuite,
    iconWrapperSuite,
    infiniteScrollSuite,
    layoutSuite,
    listSuite,
    logSuite,
    markdownStreamSuite,
    marqueeSuite,
    mentionSuite,
    numberAnimationSuite,
    pageHeaderSuite,
    popconfirmSuite,
    promptInputSuite,
    qrCodeSuite,
    questionFlowSuite,
    reasoningSuite,
    resizableSuite,
    skeletonSuite,

    spinnerSuite,

    accordionSuite,
    anchorSuite,
    approvalSuite,
    avatarSuite,
    badgeSuite,
    breadcrumbSuite,
    buttonSuite,
    calendarSuite,
    cardSuite,
    carouselSuite,
    checkboxGroupSuite,
    checkboxSuite,
    clipboardSuite,
    codeViewSuite,
    collapsibleSuite,
    comboboxSuite,
    contextMenuSuite,
    dateFieldSuite,
    datePickerSuite,
    dialogSuite,
    drawerSuite,
    editableSuite,
    fieldSuite,
    fileUploadSuite,
    hoverCardSuite,
    iconSuite,
    imageSuite,
    listboxSuite,
    menuSuite,
    navigationMenuSuite,
    notificationSuite,
    numberFieldSuite,
    paginationSuite,
    pinInputSuite,
    popoverSuite,
    progressSuite,
    radioGroupSuite,
    ratingSuite,
    scrollAreaSuite,
    scrollbarSuite,
    selectSuite,
    separatorSuite,
    sliderSuite,
    sortableSuite,
    splitterSuite,
    statisticSuite,
    stepsSuite,
    switchSuite,
    tabsSuite,
    tagsInputSuite,
    textFieldSuite,
    timeFieldSuite,
    timePickerSuite,
    timestampSuite,
    timelineSuite,
    toastSuite,
    toggleGroupSuite,
    toggleSuite,
    toolbarSuite,
    toolCallSuite,
    tooltipSuite,
    cascaderSuite,
    colorPickerSuite,
    formSuite,
    loadingBarSuite,
    menubarSuite,
    messageFeedSuite,
    tableSuite,
    tourSuite,
    transferSuite,
    typographySuite,
    virtualizerSuite,
    treeSelectSuite,
    treeSuite,
    watermarkSuite,
    tagSuite,
    segmentedSuite,
    masonrySuite,
    passwordInputSuite,
    fieldsetSuite,
    jsonViewerSuite,
    timerSuite,
    heatmapSuite,
    diffViewSuite,
    downloadTriggerSuite,
    hotkeysSuite,
    imageCropperSuite,
    signaturePadSuite,
    floatingPanelSuite,
    imageViewerSuite,
    sideNavSuite,
  ],
  { describe, it },
  {
    // 焦点环绕要真实的 Tab 焦点移动，jsdom 按 Tab 不移动焦点，这四行在这里演不出来。
    // 陷阱本身（trapped/loop 的装配）由 focus-scope 的单测覆盖，环绕效果待真机验证。
    keyboardCoverageExempt: {
      'dialog.kbd.tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'dialog.kbd.shift-tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'popover.kbd.tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'popover.kbd.shift-tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'drawer.kbd.tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'drawer.kbd.shift-tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'image-viewer.kbd.tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
      'image-viewer.kbd.shift-tab': 'jsdom 按 Tab 不移动焦点，焦点环绕演不出来',
    },
  },
)
