export { truncateAnatomy } from './truncate.anatomy'
export { connectTruncate } from './truncate.connect'
export { truncateKeyboard } from './truncate.keyboard'
export { isTruncateOverflowing, resolveTruncateLines, TRUNCATE_DEFAULT_LINES, truncateMachine } from './truncate.machine'
export { truncateMeta } from './truncate.meta'
export type { TruncateApi, TruncateExpandedChangeDetails, TruncateMetrics, TruncateOverflowChangeDetails, TruncateRefs, TruncateSchema, TruncateTranslations } from './truncate.types'
