import { toPascalCase, toKebabCase } from "@xihan-ui/utils";
import type { IconPack } from "./type";

export const icons: IconPack[] = [
  {
    id: "adi",
    name: "Ant Design Icons",
    website: "https://ant.design/components/icon",
    projectUrl: "https://github.com/ant-design/ant-design-icons",
    license: "MIT",
    licenseUrl: "https://github.com/ant-design/ant-design-icons/blob/master/LICENSE",
    source: {
      downloadUrl: "https://github.com/ant-design/ant-design-icons/archive/refs/heads/master.zip",
      localName: "ant-design-icons",
      subFolders: "packages/icons-svg/svg",
    },
    contents: [
      {
        subFolders: "filled",
        fileFilter: "*.svg",
        exportName: name => `Adi${toPascalCase(name)}Fill`,
        declareName: name => `adi-${toKebabCase(name)}-fill`,
        processWithSvgo: true,
      },
      {
        subFolders: "outlined",
        fileFilter: "*.svg",
        exportName: name => `Adi${toPascalCase(name)}Outline`,
        declareName: name => `adi-${toKebabCase(name)}-outline`,
        processWithSvgo: true,
      },
      {
        subFolders: "twotone",
        fileFilter: "*.svg",
        exportName: name => `Adi${toPascalCase(name)}Twotone`,
        declareName: name => `adi-${toKebabCase(name)}-twotone`,
        processWithSvgo: true,
        multiColor: true,
      },
    ],
  },
  {
    id: "bxi",
    name: "BoxIcons",
    website: "https://boxicons.com",
    projectUrl: "https://github.com/atisawd/boxicons",
    license: "MIT",
    licenseUrl: "https://github.com/atisawd/boxicons/blob/master/LICENSE",
    source: {
      downloadUrl: "https://github.com/atisawd/boxicons/archive/refs/heads/master.zip",
      localName: "box-icons",
      subFolders: "svg",
    },
    contents: [
      {
        subFolders: "regular",
        fileFilter: "*.svg",
        exportName: name => `Bxi${toPascalCase(name.replace("bx-", ""))}Regular`,
        declareName: name => `bxi-${toKebabCase(name.replace("bx-", ""))}-regular`,
        processWithSvgo: true,
      },
      {
        subFolders: "solid",
        fileFilter: "*.svg",
        exportName: name => `Bxi${toPascalCase(name.replace("bxs-", ""))}Solid`,
        declareName: name => `bxi-${toKebabCase(name.replace("bxs-", ""))}-solid`,
        processWithSvgo: true,
      },
      {
        subFolders: "logos",
        fileFilter: "*.svg",
        exportName: name => `Bxi${toPascalCase(name.replace("bxl-", ""))}Logo`,
        declareName: name => `bxi-${toKebabCase(name.replace("bxl-", ""))}-logo`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "bsi",
    name: "Bootstrap Icons",
    website: "https://icons.getbootstrap.com",
    projectUrl: "https://github.com/twbs/icons",
    license: "MIT",
    licenseUrl: "https://github.com/twbs/icons/blob/main/LICENSE",
    source: {
      downloadUrl: "https://github.com/twbs/icons/archive/refs/heads/main.zip",
      localName: "bootstrap",
      subFolders: "icons",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Bsi${toPascalCase(name)}`,
        declareName: name => `bsi-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "csg",
    name: "CSS.GG",
    website: "https://css.gg",
    projectUrl: "https://github.com/astrit/css.gg",
    license: "MIT",
    licenseUrl: "https://github.com/astrit/css.gg/blob/main/LICENSE.md",
    source: {
      downloadUrl: "https://github.com/astrit/css.gg/archive/refs/heads/main.zip",
      localName: "css-gg",
      subFolders: "icons/svg",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Csg${toPascalCase(name)}`,
        declareName: name => `csg-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "cii",
    name: "Circum Icons",
    website: "https://circumicons.com",
    projectUrl: "https://github.com/Klarr-Agency/Circum-Icons",
    license: "MPL-2.0",
    licenseUrl: "https://github.com/Klarr-Agency/Circum-Icons/blob/main/LICENSE",
    source: {
      downloadUrl: "https://github.com/Klarr-Agency/Circum-Icons/archive/refs/heads/main.zip",
      localName: "circum-icons",
      subFolders: "svg",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Cii${toPascalCase(name.replace(/_/g, "").replace(/&/g, "And"))}`,
        declareName: name => `cii-${toKebabCase(name.replace(/_/g, "").replace(/&/g, "And"))}`,
        processWithSvgo: true,
        multiColor: true,
      },
    ],
  },
  {
    id: "fa",
    name: "Font Awesome",
    website: "https://fontawesome.com",
    projectUrl: "https://github.com/FortAwesome/Font-Awesome",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: {
      downloadUrl: "https://github.com/FortAwesome/Font-Awesome/archive/refs/heads/6.x.zip",
      localName: "font-awesome",
      subFolders: "svgs",
    },
    contents: [
      {
        subFolders: "brands",
        fileFilter: "*.svg",
        exportName: name => `Fa${toPascalCase(name)}Brand`,
        declareName: name => `fa-${toKebabCase(name)}-brand`,
        processWithSvgo: true,
      },
      {
        subFolders: "regular",
        fileFilter: "*.svg",
        exportName: name => `Fa${toPascalCase(name)}Regular`,
        declareName: name => `fa-${toKebabCase(name)}-regular`,
        processWithSvgo: true,
      },
      {
        subFolders: "solid",
        fileFilter: "*.svg",
        exportName: name => `Fa${toPascalCase(name)}Solid`,
        declareName: name => `fa-${toKebabCase(name)}-solid`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "fci",
    name: "Flat Color Icons",
    website: "https://icons8.com/icons/color",
    projectUrl: "https://github.com/icons8/flat-color-icons",
    license: "MIT",
    licenseUrl: "https://github.com/icons8/flat-color-icons/blob/master/LICENSE.md",
    source: {
      downloadUrl: "https://github.com/icons8/flat-color-icons/archive/refs/heads/master.zip",
      localName: "flat-color-icons",
      subFolders: "svg",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Fci${toPascalCase(name)}`,
        declareName: name => `fci-${toKebabCase(name)}`,
        processWithSvgo: true,
        multiColor: true,
      },
    ],
  },
  {
    id: "fei",
    name: "Feather",
    website: "https://feathericons.com",
    projectUrl: "https://github.com/feathericons/feather",
    license: "MIT",
    licenseUrl: "https://github.com/feathericons/feather/blob/main/LICENSE",
    source: {
      downloadUrl: "https://github.com/feathericons/feather/archive/refs/heads/main.zip",
      localName: "feather-icons",
      subFolders: "icons",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Fei${toPascalCase(name)}`,
        declareName: name => `fei-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "fli",
    name: "Flag Icon",
    website: "https://flagicons.lipis.dev/",
    projectUrl: "https://github.com/lipis/flag-icons",
    license: "MIT",
    licenseUrl: "https://github.com/lipis/flag-icons/blob/main/LICENSE",
    source: {
      downloadUrl: "https://github.com/lipis/flag-icons/archive/refs/heads/main.zip",
      localName: "flag-icons",
      subFolders: "flags",
    },
    contents: [
      {
        subFolders: "4x3",
        fileFilter: "*.svg",
        exportName: name => `Fli${toPascalCase(name)}`,
        declareName: name => `fli-${toKebabCase(name)}`,
        processWithSvgo: true,
        multiColor: true,
      },
      {
        subFolders: "1x1",
        fileFilter: "*.svg",
        exportName: name => `Fli${toPascalCase(name)}Square`,
        declareName: name => `fli-${toKebabCase(name)}-square`,
        processWithSvgo: true,
        multiColor: true,
      },
    ],
  },
  {
    id: "gai",
    name: "Game Icons",
    website: "https://game-icons.net",
    projectUrl: "https://github.com/game-icons/icons",
    license: "CC BY 3.0",
    licenseUrl: "https://github.com/game-icons/icons/blob/master/license.txt",
    source: {
      downloadUrl: "https://github.com/game-icons/icons/archive/refs/heads/master.zip",
      localName: "game-icons",
      subFolders: "all-icons",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Gai${toPascalCase(name)}`,
        declareName: name => `gai-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "goi",
    name: "Github Octicons Icons",
    website: "https://primer.style/octicons",
    projectUrl: "https://github.com/primer/octicons",
    license: "MIT",
    licenseUrl: "https://github.com/primer/octicons/blob/master/LICENSE",
    source: {
      downloadUrl: "https://github.com/primer/octicons/archive/refs/heads/main.zip",
      localName: "oct-icons",
      subFolders: "icons",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*-24.svg",
        exportName: name => `Goi${toPascalCase(name.replace("-24", ""))}`,
        declareName: name => `goi-${toKebabCase(name.replace("-24", ""))}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "gri",
    name: "Grommet-Icons",
    website: "https://icons.grommet.io",
    projectUrl: "https://github.com/grommet/grommet-icons",
    license: "Apache-2.0",
    licenseUrl: "https://github.com/grommet/grommet-icons/blob/master/LICENSE",
    source: {
      downloadUrl: "https://github.com/grommet/grommet-icons/archive/refs/heads/master.zip",
      localName: "grommet-icons",
      subFolders: "public/img",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Gri${toPascalCase(name)}`,
        declareName: name => `gri-${toKebabCase(name)}`,
        processWithSvgo: true,
        multiColor: true,
      },
    ],
  },
  {
    id: "hei",
    name: "Heroicons",
    website: "https://heroicons.com",
    projectUrl: "https://github.com/tailwindlabs/heroicons",
    license: "MIT",
    licenseUrl: "https://github.com/tailwindlabs/heroicons/blob/master/LICENSE",
    source: {
      downloadUrl: "https://github.com/tailwindlabs/heroicons/archive/refs/heads/master.zip",
      localName: "heroicons",
      subFolders: "optimized",
    },
    contents: [
      {
        subFolders: "24/solid",
        fileFilter: "*.svg",
        exportName: name => `Hei${toPascalCase(name)}Solid`,
        declareName: name => `hei-${toKebabCase(name)}-solid`,
        processWithSvgo: true,
      },
      {
        subFolders: "24/outline",
        fileFilter: "*.svg",
        exportName: name => `Hei${toPascalCase(name)}Outline`,
        declareName: name => `hei-${toKebabCase(name)}-outline`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "imf",
    name: "IcoMoon Free",
    website: "https://icomoon.io",
    projectUrl: "https://github.com/Keyamoon/IcoMoon-Free",
    license: "CC BY 4.0",
    licenseUrl: "https://github.com/Keyamoon/IcoMoon-Free/blob/master/License.txt",
    source: {
      downloadUrl: "https://github.com/Keyamoon/IcoMoon-Free/archive/refs/heads/master.zip",
      localName: "icomoon-free",
      subFolders: "SVG",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Imf${toPascalCase(name.slice(4))}`,
        declareName: name => `imf-${toKebabCase(name.slice(4))}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "ioi",
    name: "Ionicons",
    website: "https://ionicons.com",
    projectUrl: "https://github.com/ionic-team/ionicons",
    license: "MIT",
    licenseUrl: "https://github.com/ionic-team/ionicons/blob/master/LICENSE",
    source: {
      downloadUrl: "https://github.com/ionic-team/ionicons/archive/refs/heads/main.zip",
      localName: "ion-icons",
      subFolders: "src/svg",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Ioi${toPascalCase(name)}`,
        declareName: name => `ioi-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "lia",
    name: "Line Awesome",
    website: "https://icons8.com/line-awesome",
    projectUrl: "https://github.com/icons8/line-awesome",
    license: "MIT",
    licenseUrl: "https://github.com/icons8/line-awesome/blob/master/LICENSE.md",
    source: {
      downloadUrl: "https://github.com/icons8/line-awesome/archive/refs/heads/master.zip",
      localName: "line-awesome",
      subFolders: "svg",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Lia${toPascalCase(name)}`,
        declareName: name => `lia-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "luc",
    name: "Lucide",
    website: "https://lucide.dev",
    projectUrl: "https://github.com/lucide-icons/lucide",
    license: "ISC",
    licenseUrl: "https://github.com/lucide-icons/lucide/blob/main/LICENSE",
    source: {
      downloadUrl: "https://github.com/lucide-icons/lucide/archive/refs/heads/main.zip",
      localName: "lucide",
      subFolders: "icons",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Luc${toPascalCase(name)}`,
        declareName: name => `luc-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "mdi",
    name: "Material Design Icons",
    website: "https://fonts.google.com/icons",
    projectUrl: "https://github.com/google/material-design-icons",
    license: "Apache-2.0",
    licenseUrl: "http://www.apache.org/licenses/",
    source: {
      downloadUrl: "https://github.com/google/material-design-icons/archive/refs/heads/master.zip",
      localName: "material-design-icons",
      subFolders: "src/*/*/*/24px.svg",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Mdi${toPascalCase(name)}`,
        declareName: name => `mdi-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "phi",
    name: "Phosphor Icons",
    website: "https://phosphoricons.com",
    projectUrl: "https://github.com/phosphor-icons/core",
    license: "MIT",
    licenseUrl: "https://github.com/phosphor-icons/core/blob/main/LICENSE",
    source: {
      downloadUrl: "https://github.com/phosphor-icons/core/archive/refs/heads/main.zip",
      localName: "phosphor-icons",
      subFolders: "assets",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*/*.svg",
        exportName: name => `Phi${toPascalCase(name)}`,
        declareName: name => `phi-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "poi",
    name: "Pokemon Icons",
    website: "https://theartificial.github.io/pokemon-icons",
    projectUrl: "https://github.com/TheArtificial/pokemon-icons",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    source: {
      downloadUrl: "https://github.com/TheArtificial/pokemon-icons/archive/refs/heads/master.zip",
      localName: "pokemon-icons",
      subFolders: "_icons/SVG",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Poi${toPascalCase(name.slice(4))}`,
        declareName: name => `poi-${toKebabCase(name.slice(4))}`,
        processWithSvgo: true,
        multiColor: true,
      },
    ],
  },
  {
    id: "rmi",
    name: "Remix Icon",
    website: "https://remixicon.com",
    projectUrl: "https://github.com/Remix-Design/RemixIcon",
    license: "Apache-2.0",
    licenseUrl: "http://www.apache.org/licenses",
    source: {
      downloadUrl: "https://github.com/Remix-Design/RemixIcon/archive/refs/heads/master.zip",
      localName: "remix-icon",
      subFolders: "icons",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*/*.svg",
        exportName: name => `Rmi${toPascalCase(name)}`,
        declareName: name => `rmi-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "rdi",
    name: "Radix Icons",
    website: "https://icons.radix-ui.com",
    projectUrl: "https://github.com/radix-ui/icons",
    license: "MIT",
    licenseUrl: "https://github.com/radix-ui/icons/blob/master/LICENSE",
    source: {
      downloadUrl: "https://github.com/radix-ui/icons/archive/refs/heads/master.zip",
      localName: "radix-icons",
      subFolders: "packages/radix-icons/icons",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Rdi${toPascalCase(name)}`,
        declareName: name => `rdi-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "sii",
    name: "Simple Icons",
    website: "https://simpleicons.org",
    projectUrl: "https://github.com/simple-icons/simple-icons",
    license: "CC0 1.0 Universal",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0",
    source: {
      downloadUrl: "https://github.com/simple-icons/simple-icons/archive/refs/heads/master.zip",
      localName: "simple-icons",
      subFolders: "icons",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Sii${toPascalCase(name)}`,
        declareName: name => `sii-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "sli",
    name: "Simple Line Icons",
    website: "https://thesabbir.github.io/simple-line-icons",
    projectUrl: "https://github.com/thesabbir/simple-line-icons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      downloadUrl: "https://github.com/thesabbir/simple-line-icons/archive/refs/heads/master.zip",
      localName: "simple-line-icons",
      subFolders: "src/svgs",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Sli${toPascalCase(name)}`,
        declareName: name => `sli-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "tbi",
    name: "Tabler Icons",
    website: "https://tabler-icons.io",
    projectUrl: "https://github.com/tabler/tabler-icons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      downloadUrl: "https://github.com/tabler/tabler-icons/archive/refs/heads/main.zip",
      localName: "tabler-icons",
      subFolders: "icons",
    },
    contents: [
      {
        subFolders: "filled",
        fileFilter: "*.svg",
        exportName: name => `Tbi${toPascalCase(name)}Filled`,
        declareName: name => `tbi-${toKebabCase(name)}-filled`,
        processWithSvgo: true,
      },
      {
        subFolders: "outline",
        fileFilter: "*.svg",
        exportName: name => `Tbi${toPascalCase(name)}Outline`,
        declareName: name => `tbi-${toKebabCase(name)}-outline`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "tfi",
    name: "Themify Icons",
    website: "https://themify.me/themify-icons",
    projectUrl: "https://github.com/lykmapipo/themify-icons",
    license: "MIT",
    licenseUrl: "https://github.com/thecreation/standard-icons/blob/master/modules/themify-icons/LICENSE",
    source: {
      downloadUrl: "https://github.com/lykmapipo/themify-icons/archive/refs/heads/master.zip",
      localName: "themify-icons",
      subFolders: "SVG",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Tfi${toPascalCase(name)}`,
        declareName: name => `tfi-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "tpi",
    name: "Typicons",
    website: "http://s-ings.com/typicons",
    projectUrl: "https://github.com/stephenhutchings/typicons.font",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: {
      downloadUrl: "https://github.com/stephenhutchings/typicons.font/archive/refs/heads/master.zip",
      localName: "typ-icons",
      subFolders: "src/svg",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Tpi${toPascalCase(name)}`,
        declareName: name => `tpi-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "vci",
    name: "VS Code Icons",
    website: "https://code.visualstudio.com",
    projectUrl: "https://github.com/microsoft/vscode-codicons",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: {
      downloadUrl: "https://github.com/microsoft/vscode-codicons/archive/refs/heads/main.zip",
      localName: "vscode-icons",
      subFolders: "src/icons",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Vci${toPascalCase(name)}`,
        declareName: name => `vci-${toKebabCase(name)}`,
        processWithSvgo: true,
      },
    ],
  },
  {
    id: "wri",
    name: "Weather Icons",
    website: "https://erikflowers.github.io/weather-icons",
    projectUrl: "https://github.com/erikflowers/weather-icons",
    license: "SIL OFL 1.1",
    licenseUrl: "http://scripts.sil.org/OFL",
    source: {
      downloadUrl: "https://github.com/erikflowers/weather-icons/archive/refs/heads/master.zip",
      localName: "weather-icons",
      subFolders: "svg",
    },
    contents: [
      {
        subFolders: "",
        fileFilter: "*.svg",
        exportName: name => `Wri${toPascalCase(name.replace("wi-", ""))}`,
        declareName: name => `wri-${toKebabCase(name.replace("wi-", ""))}`,
        processWithSvgo: true,
      },
    ],
  },
];
