import { getIconPath } from "../utils/path";
import type { IconSource } from "../utils/creator";
import { stringFormatUtils } from "@xihan-ui/utils";

export const icons: IconSource[] = [
  {
    id: "ci",
    name: "Circum Icons",
    path: "Circum-Icons",
    contents: [
      {
        files: getIconPath("../Circum-Icons/svg/*.svg"),
        formatter: (name: string) => `Ci-${name}`.replace(/_/g, "").replace(/&/g, "And"),
      },
    ],
    projectUrl: "https://circumicons.com/",
    license: "MPL-2.0 license",
    licenseUrl: "https://github.com/Klarr-Agency/Circum-Icons/blob/main/LICENSE",
    source: {
      type: "git",
      localName: "Circum-Icons",
      remoteDir: "svg",
      url: "https://github.com/Klarr-Agency/Circum-Icons.git",
      branch: "main",
      hash: "cec1364b5199f55e946a9a8360385a958b98cc60",
    },
  },
  {
    id: "fa",
    name: "Font Awesome 5",
    path: "Font-Awesome",
    contents: [
      {
        files: getIconPath("../fontawesome/svgs/+(brands|solid)/*.svg"),
        formatter: name => `Fa-${name}`,
      },
      {
        files: getIconPath("../fontawesome/svgs/regular/*.svg"),
        formatter: name => `FaReg-${name}`,
      },
    ],
    projectUrl: "https://fontawesome.com/",
    license: "CC BY 4.0 License",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    source: {
      type: "git",
      localName: "fontawesome",
      remoteDir: "svgs",
      url: "https://github.com/FortAwesome/Font-Awesome.git",
      branch: "5.x",
      hash: "afecf2af5d897b763e5e8e28d46aad2f710ccad6",
    },
  },
  {
    id: "fa6",
    name: "Font Awesome 6",
    path: "Font-Awesome",
    contents: [
      {
        files: getIconPath("../fontawesome-6/svgs/+(brands|solid)/*.svg"),
        formatter: name => `Fa-${name}`,
      },
      {
        files: getIconPath("../fontawesome-6/svgs/regular/*.svg"),
        formatter: name => `FaReg-${name}`,
      },
    ],
    projectUrl: "https://fontawesome.com/",
    license: "CC BY 4.0 License",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    source: {
      type: "git",
      localName: "fontawesome-6",
      remoteDir: "svgs",
      url: "https://github.com/FortAwesome/Font-Awesome.git",
      branch: "6.x",
      hash: "af620534bfc3c2d4cbefcfeec29603bbe7809e64",
    },
  },
  {
    id: "io",
    name: "Ionicons",
    path: "Ionicons",
    contents: [
      {
        files: getIconPath("../ionicons/src/svg/*.svg"),
        formatter: (name: string) => `Io-${name}`,
      },
    ],
    projectUrl: "https://ionicons.com/",
    license: "MIT",
    licenseUrl: "https://github.com/ionic-team/ionicons/blob/master/LICENSE",
    source: {
      type: "git",
      localName: "ionicons",
      remoteDir: "src/svg",
      url: "https://github.com/ionic-team/ionicons.git",
      branch: "main",
      hash: "4477c0251291dee6c2aeeebef8df928edf3e620f",
    },
  },
  {
    id: "ti",
    name: "Typicons",
    path: "Typicons",
    contents: [
      {
        files: getIconPath("../typicons/src/svg/*.svg"),
        formatter: name => `Ti-${name}`,
      },
    ],
    projectUrl: "http://s-ings.com/typicons/",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: {
      type: "git",
      localName: "typicons",
      remoteDir: "src/svg",
      url: "https://github.com/stephenhutchings/typicons.font.git",
      branch: "master",
      hash: "0aa64f6ce8b892a83aeeafa42c74fb9c1f22ec84",
    },
  },
  {
    id: "go",
    name: "Github Octicons icons",
    path: "Github-Octicons",
    contents: [
      {
        files: getIconPath("../../node_modules/@primer/octicons/build/svg/*-24.svg"),
        formatter: (name: string) => `Go-${name}`.replace("24", ""),
      },
    ],
    projectUrl: "https://octicons.github.com/",
    license: "MIT",
    licenseUrl: "https://github.com/primer/octicons/blob/master/LICENSE",
    source: {
      type: "git",
      localName: "typicons",
      remoteDir: "src/svg",
      url: "https://github.com/stephenhutchings/typicons.font.git",
      branch: "master",
      hash: "0aa64f6ce8b892a83aeeafa42c74fb9c1f22ec84",
    },
  },
  {
    id: "fi",
    name: "Feather",
    path: "Feather",
    contents: [
      {
        files: getIconPath("../../node_modules/feather-icons/dist/icons/*.svg"),
        formatter: (name: string) => `Fi-${name}`,
      },
    ],
    projectUrl: "https://feathericons.com/",
    license: "MIT",
    licenseUrl: "https://github.com/feathericons/feather/blob/master/LICENSE",
    source: {
      type: "git",
      localName: "typicons",
      remoteDir: "src/svg",
      url: "https://github.com/stephenhutchings/typicons.font.git",
      branch: "master",
      hash: "0aa64f6ce8b892a83aeeafa42c74fb9c1f22ec84",
    },
  },
  {
    id: "lu",
    name: "Lucide",
    path: "Lucide",
    contents: [
      {
        files: getIconPath("../lucide-static/icons/*.svg"),
        formatter: (name: string) => `Lu-${name}`,
      },
    ],
    projectUrl: "https://lucide.dev/",
    license: "ISC",
    licenseUrl: "https://github.com/lucide-icons/lucide/blob/main/LICENSE",
    source: {
      type: "git",
      localName: "typicons",
      remoteDir: "src/svg",
      url: "https://github.com/stephenhutchings/typicons.font.git",
      branch: "master",
      hash: "0aa64f6ce8b892a83aeeafa42c74fb9c1f22ec84",
    },
  },
  {
    id: "gi",
    name: "Game Icons",
    path: "Game-Icons",
    contents: [
      {
        files: getIconPath("../game-icons-inverted/all-icons/*.svg"),
        formatter: name => `Gi-${name}`,
      },
    ],
    projectUrl: "https://game-icons.net/",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    source: {
      type: "git",
      localName: "game-icons-inverted",
      remoteDir: "all-icons",
      url: "https://github.com/delacannon/game-icons-inverted.git",
      branch: "master",
      hash: "12920d6565588f0512542a3cb0cdfd36a497f910",
    },
  },
  {
    id: "wi",
    name: "Weather Icons",
    path: "Weather-Icons",
    contents: [
      {
        files: getIconPath("../weather-icons/svg/*.svg"),
        formatter: name => name,
      },
    ],
    projectUrl: "https://erikflowers.github.io/weather-icons/",
    license: "SIL OFL 1.1",
    licenseUrl: "http://scripts.sil.org/OFL",
    source: {
      type: "git",
      localName: "weather-icons",
      remoteDir: "svg",
      url: "https://github.com/erikflowers/weather-icons.git",
      branch: "master",
      hash: "bb80982bf1f43f2d57f9dd753e7413bf88beb9ed",
    },
  },
  {
    id: "di",
    name: "Devicons",
    path: "Devicons",
    contents: [
      {
        files: getIconPath("../devicons/!SVG/*.svg"),
        formatter: name => `Di-${name}`,
      },
    ],
    projectUrl: "https://vorillaz.github.io/devicons/",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "devicons",
      remoteDir: "!SVG",
      url: "https://github.com/vorillaz/devicons.git",
      branch: "master",
      hash: "ba75593fdf8d66496676a90cbf127d721f73e961",
    },
  },
  {
    id: "ai",
    name: "Ant Design Icons",
    path: "Ant-Design-Icons",
    contents: [
      {
        files: getIconPath("../ant-design-icons/packages/icons-svg/svg/filled/*.svg"),
        formatter: name => `AiFill-${name}`,
      },
      {
        files: getIconPath("../ant-design-icons/packages/icons-svg/svg/outlined/*.svg"),
        formatter: name => `AiOutline-${name}`,
      },
      {
        files: getIconPath("../ant-design-icons/packages/icons-svg/svg/twotone/*.svg"),
        formatter: name => `AiTwotone-${name}`,
        multiColor: true,
      },
    ],
    projectUrl: "https://github.com/ant-design/ant-design-icons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "ant-design-icons",
      remoteDir: "packages/icons-svg/svg",
      url: "https://github.com/ant-design/ant-design-icons.git",
      branch: "master",
      hash: "c40b685dd7eb079162cbb53398da874fd03070e2",
    },
  },
  // {
  //   id: "bs",
  //   name: "Bootstrap Icons",
  //   path: "Bootstrap-Icons",
  //   contents: [
  //     {
  //       files: getIconPath("../bootstrap/icons/*!(-reverse)-fill.svg"),
  //       formatter: name => `BsFill-${name}`,
  //     },
  //     {
  //       files: getIconPath("../bootstrap/icons/*-reverse!(-fill).svg"),
  //       formatter: name => `BsReverse-${name}`,
  //     },
  //     {
  //       files: getIconPath("../bootstrap/icons/*!(-fill|-reverse|reverse-).svg"),
  //       formatter: name => `Bs-${name}`,
  //     },
  //   ],
  //   projectUrl: "https://github.com/twbs/icons",
  //   license: "MIT",
  //   licenseUrl: "https://opensource.org/licenses/MIT",
  //   source: {
  //     type: "git",
  //     localName: "bootstrap",
  //     remoteDir: "icons",
  //     url: "https://github.com/twbs/icons.git",
  //     branch: "main",
  //     hash: "e898da7559e12643a9b5a26f96d2b669a5dc3d8f",
  //   },
  // },
  {
    id: "ri",
    name: "Remix Icon",
    path: "Remix-Icon",
    contents: [
      {
        files: getIconPath("../RemixIcon/icons/*/*.svg"),
        formatter: name => `Ri-${name}`,
      },
    ],
    projectUrl: "https://github.com/Remix-Design/RemixIcon",
    license: "Apache License Version 2.0",
    licenseUrl: "http://www.apache.org/licenses/",
    source: {
      type: "git",
      localName: "RemixIcon",
      remoteDir: "icons",
      url: "https://github.com/Remix-Design/RemixIcon.git",
      branch: "master",
      hash: "8bc436bdd329cf342958d8effdd078bfa74354c6",
    },
  },
  {
    id: "fc",
    name: "Flat Color Icons",
    path: "Flat-Color-Icons",
    contents: [
      {
        files: getIconPath("../flat-color-icons/svg/*.svg"),
        formatter: name => `Fc-${name}`,
        multiColor: true,
      },
    ],
    projectUrl: "https://github.com/icons8/flat-color-icons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "flat-color-icons",
      remoteDir: "svg",
      url: "https://github.com/icons8/flat-color-icons.git",
      branch: "master",
      hash: "8eccbbbd8b2af1d2c9593e7cfba5ecb0d68ee378",
    },
  },
  {
    id: "gr",
    name: "Grommet-Icons",
    path: "Grommet-Icons",
    contents: [
      {
        files: getIconPath("../grommet-icons/public/img/*.svg"),
        formatter: name => `Gr-${name}`,
      },
    ],
    projectUrl: "https://github.com/grommet/grommet-icons",
    license: "Apache License Version 2.0",
    licenseUrl: "http://www.apache.org/licenses/",
    source: {
      type: "git",
      localName: "grommet-icons",
      remoteDir: "public/img",
      url: "https://github.com/grommet/grommet-icons.git",
      branch: "master",
      hash: "469590e6fb8b7a684756308f96a45a8425580f05",
    },
  },
  {
    id: "hi",
    name: "Heroicons",
    path: "Heroicons",
    contents: [
      {
        files: getIconPath("../heroicons/optimized/solid/*.svg"),
        formatter: name => `Hi-${name}`,
      },
      {
        files: getIconPath("../heroicons/optimized/outline/*.svg"),
        formatter: name => `HiOutline-${name}`,
      },
    ],
    projectUrl: "https://github.com/tailwindlabs/heroicons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "heroicons",
      remoteDir: "optimized",
      url: "https://github.com/tailwindlabs/heroicons.git",
      branch: "v1",
      hash: "b6de5792d3d53ff81c71b1b8283463aad622e0e3",
    },
  },
  {
    id: "hi2",
    name: "Heroicons 2",
    path: "Heroicons",
    contents: [
      {
        files: getIconPath("../heroicons-2/optimized/24/solid/*.svg"),
        formatter: name => `Hi-${name}`,
      },
      {
        files: getIconPath("../heroicons-2/optimized/24/outline/*.svg"),
        formatter: name => `HiOutline-${name}`,
      },
      {
        files: getIconPath("../heroicons-2/optimized/20/solid/*.svg"),
        formatter: name => `HiMini-${name}`,
      },
    ],
    projectUrl: "https://github.com/tailwindlabs/heroicons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "heroicons-2",
      remoteDir: "optimized",
      url: "https://github.com/tailwindlabs/heroicons.git",
      branch: "master",
      hash: "fa902f44d071eac776758cfd6e0522cb7c37b1c3",
    },
  },
  {
    id: "si",
    name: "Simple Icons",
    path: "Simple-Icons",
    contents: [
      {
        files: getIconPath("../simple-icons/icons/*.svg"),
        formatter: name => `Si-${name}`,
      },
    ],
    projectUrl: "https://simpleicons.org/",
    license: "CC0 1.0 Universal",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: {
      type: "git",
      localName: "simple-icons",
      remoteDir: "icons",
      url: "https://github.com/simple-icons/simple-icons.git",
      branch: "develop",
      hash: "6b348d4987613d568d12a862ad2b97a3f66fda52",
    },
  },
  {
    id: "sl",
    name: "Simple Line Icons",
    path: "Simple-Line-Icons",
    contents: [
      {
        files: getIconPath("../simple-line-icons/src/svgs/*.svg"),
        formatter: name => `Sl-${name}`,
      },
    ],
    projectUrl: "https://thesabbir.github.io/simple-line-icons/",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "simple-line-icons",
      remoteDir: "src/svgs",
      url: "https://github.com/thesabbir/simple-line-icons.git",
      branch: "master",
      hash: "f3ed94dd797bdcab52d6f27ba589aea4bb6f3e4d",
    },
  },
  {
    id: "im",
    name: "IcoMoon Free",
    path: "IcoMoon-Free",
    contents: [
      {
        files: getIconPath("../icomoon-free/SVG/*.svg"),
        formatter: name => `Im${name.slice(3)}`,
      },
    ],
    projectUrl: "https://github.com/Keyamoon/IcoMoon-Free",
    license: "CC BY 4.0 License",
    licenseUrl: "https://github.com/Keyamoon/IcoMoon-Free/blob/master/License.txt",
    source: {
      type: "git",
      localName: "icomoon-free",
      remoteDir: "SVG",
      url: "https://github.com/Keyamoon/IcoMoon-Free.git",
      branch: "master",
      hash: "d006795ede82361e1bac1ee76f215cf1dc51e4ca",
    },
  },
  {
    id: "bi",
    name: "BoxIcons",
    path: "BoxIcons",
    contents: [
      {
        files: getIconPath("../boxicons/svg/regular/*.svg"),
        formatter: name => `Bi${name.replace("Bx", "")}`,
      },
      {
        files: getIconPath("../boxicons/svg/solid/*.svg"),
        formatter: name => `BiSolid${name.replace("Bxs", "")}`,
      },
      {
        files: getIconPath("../boxicons/svg/logos/*.svg"),
        formatter: name => `BiLogo${name.replace("Bxl", "")}`,
      },
    ],
    projectUrl: "https://github.com/atisawd/boxicons",
    license: "MIT",
    licenseUrl: "https://github.com/atisawd/boxicons/blob/master/LICENSE",
    source: {
      type: "git",
      localName: "boxicons",
      remoteDir: "svg",
      url: "https://github.com/atisawd/boxicons.git",
      branch: "master",
      hash: "9ffa9136e8681886bb7bd2145cd4098717ce1c11",
    },
  },
  {
    id: "cg",
    name: "css.gg",
    path: "Css-Gg",
    contents: [
      {
        files: getIconPath("../css.gg/icons/svg/*.svg"),
        formatter: name => `Cg-${name}`,
      },
    ],
    projectUrl: "https://github.com/astrit/css.gg",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "css.gg",
      remoteDir: "icons/svg",
      url: "https://github.com/astrit/css.gg.git",
      branch: "main",
      hash: "ad0428df5491082b29a81d64dbdc59b9602cc059",
    },
  },
  {
    id: "vsc",
    name: "VS Code Icons",
    path: "VS-Code-Icons",
    contents: [
      {
        files: getIconPath("../vscode-icons/src/icons/*.svg"),
        formatter: name => `Vsc-${name}`,
      },
    ],
    projectUrl: "https://github.com/microsoft/vscode-codicons",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    source: {
      type: "git",
      localName: "vscode-icons",
      remoteDir: "src/icons",
      url: "https://github.com/microsoft/vscode-codicons.git",
      branch: "main",
      hash: "a7c0d645fae136004f6af65b66a084747d36be37",
    },
  },
  {
    id: "tb",
    name: "Tabler Icons",
    path: "Tabler-Icons",
    contents: [
      {
        files: getIconPath("../tabler-icons/icons/filled/*.svg"),
        formatter: name => `Tb-${name}Filled`,
      },
      {
        files: getIconPath("../tabler-icons/icons/outline/*.svg"),
        formatter: name => `Tb-${name}`,
      },
    ],
    projectUrl: "https://github.com/tabler/tabler-icons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "tabler-icons",
      remoteDir: "icons",
      url: "https://github.com/tabler/tabler-icons.git",
      branch: "main",
      hash: "a90ddb1fb22fbb28bcafcace6a43fe66ff1f16e2",
    },
  },
  {
    id: "tfi",
    name: "Themify Icons",
    path: "Themify-Icons",
    contents: [
      {
        files: getIconPath("../themify-icons/SVG/*.svg"),
        formatter: name => `Tfi-${name}`,
      },
    ],
    projectUrl: "https://github.com/lykmapipo/themify-icons",
    license: "MIT",
    licenseUrl: "https://github.com/thecreation/standard-icons/blob/master/modules/themify-icons/LICENSE",
    source: {
      type: "git",
      localName: "themify-icons",
      remoteDir: "SVG",
      url: "https://github.com/lykmapipo/themify-icons.git",
      branch: "master",
      hash: "9600186b24a7242f0e1e0a186983e6253301bb5d",
    },
  },
  {
    id: "rx",
    name: "Radix Icons",
    path: "Radix-Icons",
    contents: [
      {
        files: getIconPath("../radix-icons/packages/radix-icons/icons/*.svg"),
        formatter: name => `Rx${stringFormatUtils.toPascalCase(name)}`,
      },
    ],
    projectUrl: "https://icons.radix-ui.com",
    license: "MIT",
    licenseUrl: "https://github.com/radix-ui/icons/blob/master/LICENSE",
    source: {
      type: "git",
      localName: "radix-icons",
      remoteDir: "packages/radix-icons/icons",
      url: "https://github.com/radix-ui/icons.git",
      branch: "master",
      hash: "bde33b13aa5848555f5512ac12155930fb4beb7d",
    },
  },
  {
    id: "pi",
    name: "Phosphor Icons",
    path: "Phosphor-Icons",
    contents: [
      {
        files: getIconPath("../phosphor-icons/assets/*/*.svg"),
        formatter: name => `Pi-${name}`,
      },
    ],
    projectUrl: "https://github.com/phosphor-icons/core",
    license: "MIT",
    licenseUrl: "https://github.com/phosphor-icons/core/blob/main/LICENSE",
    source: {
      type: "git",
      localName: "phosphor-icons",
      remoteDir: "assets",
      url: "https://github.com/phosphor-icons/core.git",
      branch: "main",
      hash: "718275586082878c7c7d220ad350db2962d749e6",
    },
  },
  {
    id: "lia",
    name: "Icons8 Line Awesome",
    path: "Line-Awesome",
    contents: [
      {
        files: getIconPath("../line-awesome/svg/*.svg"),
        formatter: name => `Lia-${name}`,
      },
    ],
    projectUrl: "https://icons8.com/line-awesome",
    license: "MIT",
    licenseUrl: "https://github.com/icons8/line-awesome/blob/master/LICENSE.md",
    source: {
      type: "git",
      localName: "line-awesome",
      remoteDir: "svg",
      url: "https://github.com/icons8/line-awesome.git",
      branch: "master",
      hash: "78a101217707c9b1c4dcf2a821be75684e36307f",
    },
  },
];
