import type { IconSource } from "../utils/creator";

export const icons: IconSource[] = [
  {
    id: "ci",
    name: "Circum Icons",
    path: "Circum-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: (name: string) => `Ci-${name}`.replace(/_/g, "").replace(/&/g, "And"),
      },
    ],
    projectUrl: "https://circumicons.com/",
    license: "MPL-2.0 license",
    licenseUrl: "https://github.com/Klarr-Agency/Circum-Icons/blob/main/LICENSE",
    source: {
      type: "git",
      localName: "circum-icons",
      subFolders: "svg",
      url: "https://github.com/Klarr-Agency/Circum-Icons.git",
      branch: "main",
      hash: "cec1364b5199f55e946a9a8360385a958b98cc60",
    },
  },
  {
    id: "fa",
    name: "Font Awesome",
    path: "Font-Awesome",
    contents: [
      {
        fileFilter: "brands/*.svg",
        formatter: (name: string) => `Fa-${name}Brand`,
      },
      {
        fileFilter: "regular/*.svg",
        formatter: (name: string) => `Fa-${name}Regular`,
      },
      {
        fileFilter: "solid/*.svg",
        formatter: (name: string) => `Fa-${name}Solid`,
      },
    ],
    projectUrl: "https://fontawesome.com/",
    license: "CC BY 4.0 License",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    source: {
      type: "git",
      localName: "font-awesome",
      subFolders: "svgs",
      url: "https://github.com/FortAwesome/Font-Awesome.git",
      branch: "6.x",
      hash: "af620534bfc3c2d4cbefcfeec29603bbe7809e64",
    },
  },
  {
    id: "io",
    name: "Ionicons",
    path: "Ionicons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: (name: string) => `Io-${name}`,
      },
    ],
    projectUrl: "https://ionicons.com/",
    license: "MIT",
    licenseUrl: "https://github.com/ionic-team/ionicons/blob/master/LICENSE",
    source: {
      type: "git",
      localName: "ion-icons",
      subFolders: "src/svg",
      url: "https://github.com/ionic-team/ionicons.git",
      branch: "main",
      hash: "4477c0251291dee6c2aeeebef8df928edf3e620f",
    },
  },
  {
    id: "ti",
    name: "Typicons",
    path: "Typicons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: (name: string) => `Ti-${name}`,
      },
    ],
    projectUrl: "http://s-ings.com/typicons/",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: {
      type: "git",
      localName: "typ-icons",
      subFolders: "src/svg",
      url: "https://github.com/stephenhutchings/typicons.font.git",
      branch: "master",
      hash: "0aa64f6ce8b892a83aeeafa42c74fb9c1f22ec84",
    },
  },
  {
    id: "go",
    name: "Github Octicons icons",
    path: "Github-Octicons",
    contents: [
      {
        fileFilter: "*-24.svg",
        formatter: (name: string) => `Go-${name.replace("-24", "")}`,
      },
    ],
    projectUrl: "https://octicons.github.com/",
    license: "MIT",
    licenseUrl: "https://github.com/primer/octicons/blob/master/LICENSE",
    source: {
      type: "git",
      localName: "oct-icons",
      subFolders: "icons",
      url: "https://github.com/primer/octicons.git",
      branch: "main",
      hash: "863af9507f27e8e99f13237873c0a1897eaf5640",
    },
  },
  {
    id: "fi",
    name: "Feather",
    path: "Feather",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: (name: string) => `Fi-${name}`,
      },
    ],
    projectUrl: "https://feathericons.com/",
    license: "MIT",
    licenseUrl: "https://github.com/feathericons/feather/blob/master/LICENSE",
    source: {
      type: "git",
      localName: "feather-icons",
      subFolders: "icons",
      url: "https://github.com/feathericons/feather.git",
      branch: "main",
      hash: "3dc050d97405062eba78aa57115c0a15c63abdaa",
    },
  },
  {
    id: "lu",
    name: "Lucide",
    path: "Lucide",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: (name: string) => `Lu-${name}`,
      },
    ],
    projectUrl: "https://lucide.dev/",
    license: "ISC",
    licenseUrl: "https://github.com/lucide-icons/lucide/blob/main/LICENSE",
    source: {
      type: "git",
      localName: "lucide",
      subFolders: "icons",
      url: "https://github.com/lucide-icons/lucide.git",
      branch: "main",
      hash: "5f5e052038f364b97d7310c0ac6ee686b90051f4",
    },
  },
  {
    id: "gi",
    name: "Game Icons",
    path: "Game-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: (name: string) => `Gi-${name}`,
      },
    ],
    projectUrl: "https://game-icons.net/",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    source: {
      type: "git",
      localName: "game-icons-inverted",
      subFolders: "all-icons",
      url: "https://github.com/delacannon/game-icons-inverted.git",
      branch: "master",
      hash: "12920d6565588f0512542a3cb0cdfd36a497f910",
    },
  },
  {
    id: "wi",
    name: "Weather Icons",
    path: "Weather-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: (name: string) => `Wi-${name.replace("wi-", "")}`,
      },
    ],
    projectUrl: "https://erikflowers.github.io/weather-icons/",
    license: "SIL OFL 1.1",
    licenseUrl: "http://scripts.sil.org/OFL",
    source: {
      type: "git",
      localName: "weather-icons",
      subFolders: "svg",
      url: "https://github.com/erikflowers/weather-icons.git",
      branch: "master",
      hash: "bb80982bf1f43f2d57f9dd753e7413bf88beb9ed",
    },
  },
  {
    id: "di",
    name: "Devicons",
    path: "Devicons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: (name: string) => `Di-${name}`,
      },
    ],
    projectUrl: "https://vorillaz.github.io/devicons/",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "dev-icons",
      subFolders: "!SVG",
      url: "https://github.com/vorillaz/devicons.git",
      branch: "master",
      hash: "ba75593fdf8d66496676a90cbf127d721f73e961",
    },
  },
  {
    id: "ai",
    name: "Ant Design Icons",
    path: "Ant-Design-Icons",
    contents: [
      {
        fileFilter: "filled/*.svg",
        formatter: (name: string) => `Ai-${name}Fill`,
      },
      {
        fileFilter: "outlined/*.svg",
        formatter: (name: string) => `Ai-${name}Outline`,
      },
      {
        fileFilter: "twotone/*.svg",
        formatter: (name: string) => `Ai-${name}Twotone`,
        multiColor: true,
      },
    ],
    projectUrl: "https://github.com/ant-design/ant-design-icons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "ant-design-icons",
      subFolders: "packages/icons-svg/svg",
      url: "https://github.com/ant-design/ant-design-icons.git",
      branch: "master",
      hash: "c40b685dd7eb079162cbb53398da874fd03070e2",
    },
  },
  {
    id: "bs",
    name: "Bootstrap Icons",
    path: "Bootstrap-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Bs-${name}`,
      },
    ],
    projectUrl: "https://github.com/twbs/icons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "bootstrap",
      subFolders: "icons",
      url: "https://github.com/twbs/icons.git",
      branch: "main",
      hash: "e898da7559e12643a9b5a26f96d2b669a5dc3d8f",
    },
  },
  {
    id: "ri",
    name: "Remix Icon",
    path: "Remix-Icon",
    contents: [
      {
        fileFilter: "*/*.svg",
        formatter: name => `Ri-${name}`,
      },
    ],
    projectUrl: "https://github.com/Remix-Design/RemixIcon",
    license: "Apache License Version 2.0",
    licenseUrl: "http://www.apache.org/licenses/",
    source: {
      type: "git",
      localName: "remix-icon",
      subFolders: "icons",
      url: "https://github.com/Remix-Design/RemixIcon.git",
      branch: "master",
      hash: "8bc436bdd329cf342958d8effdd078bfa74354c6",
    },
  },
  {
    id: "fc",
    name: "Flat Color Icons",
    path: "Flat-Color-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Fc-${name}`,
        multiColor: true,
      },
    ],
    projectUrl: "https://github.com/icons8/flat-color-icons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "flat-color-icons",
      subFolders: "svg",
      url: "https://github.com/icons8/flat-color-icons.git",
      branch: "master",
      hash: "8eccbbbd8b2af1d2c9593e7cfba5ecb0d68ee378",
    },
  },
  {
    id: "gr",
    name: "Grommet-Icons",
    path: "Grommet-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Gr-${name}`,
      },
    ],
    projectUrl: "https://github.com/grommet/grommet-icons",
    license: "Apache License Version 2.0",
    licenseUrl: "http://www.apache.org/licenses/",
    source: {
      type: "git",
      localName: "grommet-icons",
      subFolders: "public/img",
      url: "https://github.com/grommet/grommet-icons.git",
      branch: "master",
      hash: "469590e6fb8b7a684756308f96a45a8425580f05",
    },
  },
  {
    id: "hi",
    name: "Heroicons",
    path: "Heroicons",
    contents: [
      {
        fileFilter: "24/solid/*.svg",
        formatter: (name: string) => `Hi-${name}Solid`,
      },
      {
        fileFilter: "24/outline/*.svg",
        formatter: (name: string) => `Hi-${name}Outline`,
      },
    ],
    projectUrl: "https://github.com/tailwindlabs/heroicons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "heroicons",
      subFolders: "optimized",
      url: "https://github.com/tailwindlabs/heroicons.git",
      branch: "master",
      hash: "fa902f44d071eac776758cfd6e0522cb7c37b1c3",
    },
  },
  {
    id: "si",
    name: "Simple Icons",
    path: "Simple-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Si-${name}`,
      },
    ],
    projectUrl: "https://simpleicons.org/",
    license: "CC0 1.0 Universal",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: {
      type: "git",
      localName: "simple-icons",
      subFolders: "icons",
      url: "https://github.com/simple-icons/simple-icons.git",
      branch: "master",
      hash: "2aef7ce65fbaef8a013d254d3ee98cbf054a6aad",
    },
  },
  {
    id: "sl",
    name: "Simple Line Icons",
    path: "Simple-Line-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Sl-${name}`,
      },
    ],
    projectUrl: "https://thesabbir.github.io/simple-line-icons/",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "simple-line-icons",
      subFolders: "src/svgs",
      url: "https://github.com/thesabbir/simple-line-icons.git",
      branch: "master",
      hash: "f3ed94dd797bdcab52d6f27ba589aea4bb6f3e4d",
    },
  },
  {
    id: "im",
    name: "IcoMoon Free",
    path: "IcoMoon-Free",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Im-${name.slice(4).toLowerCase()}`,
      },
    ],
    projectUrl: "https://github.com/Keyamoon/IcoMoon-Free",
    license: "CC BY 4.0 License",
    licenseUrl: "https://github.com/Keyamoon/IcoMoon-Free/blob/master/License.txt",
    source: {
      type: "git",
      localName: "icomoon-free",
      subFolders: "SVG",
      url: "https://github.com/Keyamoon/IcoMoon-Free.git",
      branch: "master",
      hash: "d006795ede82361e1bac1ee76f215cf1dc51e4ca",
    },
  },
  {
    id: "bi",
    name: "BoxIcons",
    path: "BoxIcons",
    contents: [
      {
        fileFilter: "regular/*.svg",
        formatter: name => `Bi-${name.replace("bx-", "")}Regular`,
      },
      {
        fileFilter: "solid/*.svg",
        formatter: name => `Bi-${name.replace("bxs-", "")}Solid`,
      },
      {
        fileFilter: "logos/*.svg",
        formatter: name => `Bi-${name.replace("bxl-", "")}Logo`,
      },
    ],
    projectUrl: "https://github.com/atisawd/boxicons",
    license: "MIT",
    licenseUrl: "https://github.com/atisawd/boxicons/blob/master/LICENSE",
    source: {
      type: "git",
      localName: "box-icons",
      subFolders: "svg",
      url: "https://github.com/atisawd/boxicons.git",
      branch: "master",
      hash: "9ffa9136e8681886bb7bd2145cd4098717ce1c11",
    },
  },
  {
    id: "cg",
    name: "css.gg",
    path: "Css-Gg",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Cg-${name}`,
      },
    ],
    projectUrl: "https://github.com/astrit/css.gg",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "css-gg",
      subFolders: "icons/svg",
      url: "https://github.com/astrit/css.gg.git",
      branch: "main",
      hash: "ad0428df5491082b29a81d64dbdc59b9602cc059",
    },
  },
  {
    id: "vsc",
    name: "VS Code Icons",
    path: "VS-Code-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Vsc-${name}`,
      },
    ],
    projectUrl: "https://github.com/microsoft/vscode-codicons",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    source: {
      type: "git",
      localName: "vscode-icons",
      subFolders: "src/icons",
      url: "https://github.com/microsoft/vscode-codicons.git",
      branch: "main",
      hash: "a7c0d645fae136004f6af65b66a084747d36be37",
    },
  },
  {
    id: "tb",
    name: "Tabler Icons",
    path: "Tabler-Icons",
    contents: [
      {
        fileFilter: "filled/*.svg",
        formatter: name => `Tb-${name}Filled`,
      },
      {
        fileFilter: "outline/*.svg",
        formatter: name => `Tb-${name}Outline`,
      },
    ],
    projectUrl: "https://github.com/tabler/tabler-icons",
    license: "MIT",
    licenseUrl: "https://opensource.org/licenses/MIT",
    source: {
      type: "git",
      localName: "tabler-icons",
      subFolders: "icons",
      url: "https://github.com/tabler/tabler-icons.git",
      branch: "main",
      hash: "a90ddb1fb22fbb28bcafcace6a43fe66ff1f16e2",
    },
  },
  {
    id: "tfi",
    name: "Themify Icons",
    path: "Themify-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Tfi-${name.toLowerCase()}`,
      },
    ],
    projectUrl: "https://github.com/lykmapipo/themify-icons",
    license: "MIT",
    licenseUrl: "https://github.com/thecreation/standard-icons/blob/master/modules/themify-icons/LICENSE",
    source: {
      type: "git",
      localName: "themify-icons",
      subFolders: "SVG",
      url: "https://github.com/lykmapipo/themify-icons.git",
      branch: "master",
      hash: "9600186b24a7242f0e1e0a186983e6253301bb5d",
    },
  },
  {
    id: "rx",
    name: "Radix Icons",
    path: "Radix-Icons",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Rx-${name}`,
      },
    ],
    projectUrl: "https://icons.radix-ui.com",
    license: "MIT",
    licenseUrl: "https://github.com/radix-ui/icons/blob/master/LICENSE",
    source: {
      type: "git",
      localName: "radix-icons",
      subFolders: "packages/radix-icons/icons",
      url: "https://github.com/radix-ui/icons.git",
      branch: "master",
      hash: "bde33b13aa5848555f5512ac12155930fb4beb7d",
    },
  },
  {
    id: "pi",
    name: "Phosphor Icons",
    path: "Phosphor-Icons",
    contents: [
      {
        fileFilter: "*/*.svg",
        formatter: name => `Pi-${name}`,
      },
    ],
    projectUrl: "https://github.com/phosphor-icons/core",
    license: "MIT",
    licenseUrl: "https://github.com/phosphor-icons/core/blob/main/LICENSE",
    source: {
      type: "git",
      localName: "phosphor-icons",
      subFolders: "assets",
      url: "https://github.com/phosphor-icons/core.git",
      branch: "main",
      hash: "718275586082878c7c7d220ad350db2962d749e6",
    },
  },
  {
    id: "lia",
    name: "Icons8 Line Awesome",
    path: "Line-Awesome",
    contents: [
      {
        fileFilter: "*.svg",
        formatter: name => `Lia-${name}`,
      },
    ],
    projectUrl: "https://icons8.com/line-awesome",
    license: "MIT",
    licenseUrl: "https://github.com/icons8/line-awesome/blob/master/LICENSE.md",
    source: {
      type: "git",
      localName: "line-awesome",
      subFolders: "svg",
      url: "https://github.com/icons8/line-awesome.git",
      branch: "master",
      hash: "78a101217707c9b1c4dcf2a821be75684e36307f",
    },
  },
];
