export { separatorAnatomy } from './separator.anatomy'
export { connectSeparator } from './separator.connect'
export { separatorKeyboard } from './separator.keyboard'
export { separatorMeta } from './separator.meta'
export type { SeparatorAlign, SeparatorApi, SeparatorProps, SeparatorTranslations, SeparatorVariant } from './separator.types'
