export { detectHotkeysPlatform, formatHotkey, isTypingTarget, matchesHotkey, resolveHotkeysPlatform } from '../shared/hotkey'
export type { HotkeySegment, HotkeysPlatform, HotkeysResolvedPlatform } from '../shared/hotkey'
export { hotkeysAnatomy } from './hotkeys.anatomy'
export { connectHotkeys } from './hotkeys.connect'
export { hotkeysKeyboard } from './hotkeys.keyboard'
export { hotkeysMeta } from './hotkeys.meta'
export type { HotkeysApi, HotkeysProps, HotkeysTarget, HotkeysTriggerDetails } from './hotkeys.types'
