export { hotkeysAnatomy } from './hotkeys.anatomy'
export { connectHotkeys } from './hotkeys.connect'
export { hotkeysKeyboard } from './hotkeys.keyboard'
export { detectHotkeysPlatform, formatHotkey, isTypingTarget, matchesHotkey, resolveHotkeysPlatform } from './hotkeys.keys'
export type { HotkeySegment, HotkeysPlatform, HotkeysResolvedPlatform } from './hotkeys.keys'
export { hotkeysMeta } from './hotkeys.meta'
export type { HotkeysApi, HotkeysKeyProps, HotkeysProps, HotkeysTarget, HotkeysTranslations, HotkeysTriggerDetails } from './hotkeys.types'
