// gate 的模块清单：pnpm gate 按这里的先后逐模块、逐步串行执行；pnpm gate <模块…> 只跑点名的模块。
// 每一步是一条命令（与 package.json script 同写法），check-wiring 把这里当作接线来源。
// 模块目录与这里的 id 一一对应：tooling/scripts/<id>/check-*.mjs；不在 gate 里的检查（发布前产物、
// 文档站构建后才能核的那几道）同样按职责放在模块目录里，由 package.json 的 gate:* 单独调用。

/** @typedef {{ id: string, label: string, steps: string[] }} GateModule */

/** @type {GateModule[]} */
export const MODULES = [
  {
    id: 'package',
    label: '包与发布',
    steps: [
      'node tooling/scripts/package/check-runtime-deps.mjs',
      'node tooling/scripts/package/check-exact-pins.mjs',
      'node tooling/scripts/package/check-version-lock.mjs',
      'node tooling/scripts/package/check-exports.mjs',
      'node tooling/scripts/package/check-package-roles.mjs',
      'node tooling/scripts/package/check-package-manifests.mjs',
      'node tooling/scripts/package/check-published-refs.mjs',
    ],
  },
  {
    id: 'tokens',
    label: '令牌与取值',
    steps: [
      'node tooling/scripts/tokens/check-tokens-dist.mjs',
      'pnpm gate:component-tokens',
      'node tooling/scripts/tokens/check-layer-order.mjs',
      'node tooling/scripts/tokens/check-raw-zindex.mjs',
      'node tooling/scripts/tokens/check-token-refs.mjs',
      'node tooling/scripts/tokens/check-shared-slots.mjs',
      'node tooling/scripts/tokens/check-literal-fallbacks.mjs',
      'node tooling/scripts/tokens/check-color-literals.mjs',
      'node tooling/scripts/tokens/check-tone-contrast.mjs',
      'node tooling/scripts/tokens/check-tone-tokens.mjs',
      'node tooling/scripts/tokens/check-private-slots.mjs',
      'node tooling/scripts/tokens/check-disabled-contrast.mjs',
      'node tooling/scripts/tokens/check-breakpoints.mjs',
    ],
  },
  {
    id: 'skin',
    label: '皮肤结构与环境档',
    steps: [
      'node tooling/scripts/skin/check-style-entries.mjs',
      'node tooling/scripts/skin/check-skin-markers.mjs',
      'node tooling/scripts/skin/check-hidden-override.mjs',
      'node tooling/scripts/skin/check-undefined-guard.mjs',
      'node tooling/scripts/skin/check-skin-size.mjs',
      'node tooling/scripts/skin/check-scope-has-skin.mjs',
      'node tooling/scripts/skin/check-skin-parts.mjs',
      'node tooling/scripts/skin/check-visually-hidden.mjs',
      'node tooling/scripts/skin/check-axis-declaration.mjs',
      'node tooling/scripts/skin/check-placeholder-fg.mjs',
      'node tooling/scripts/skin/check-autofill.mjs',
      'node tooling/scripts/skin/check-container-scope.mjs',
      'node tooling/scripts/skin/check-css-floor.mjs',
      'node tooling/scripts/skin/check-print-surface.mjs',
      'node tooling/scripts/skin/check-forced-colors.mjs',
      'node tooling/scripts/skin/check-safe-area.mjs',
    ],
  },
  {
    id: 'visual',
    label: '尺度、阶梯与家族配方',
    steps: [
      'node tooling/scripts/visual/check-shape-scale.mjs',
      'node tooling/scripts/visual/check-spacing-slots.mjs',
      'node tooling/scripts/visual/check-stroke-scale.mjs',
      'node tooling/scripts/visual/check-text-scale.mjs',
      'node tooling/scripts/visual/check-elevation-role.mjs',
      'node tooling/scripts/visual/check-surface-edge.mjs',
      'node tooling/scripts/visual/check-selection-marker.mjs',
      'node tooling/scripts/visual/check-state-ladder.mjs',
      'node tooling/scripts/visual/check-text-role.mjs',
      'node tooling/scripts/visual/check-control-height.mjs',
      'node tooling/scripts/visual/check-size-ladder.mjs',
      'node tooling/scripts/visual/check-control-box.mjs',
      'node tooling/scripts/visual/check-panel-height.mjs',
      'node tooling/scripts/visual/check-family-parity.mjs',
      'pnpm gate:family',
      'node tooling/scripts/visual/check-glyph-slots.mjs',
      'node tooling/scripts/visual/check-glyph-layer.mjs',
      'node tooling/scripts/visual/check-icon-size.mjs',
      'node tooling/scripts/visual/check-press-feedback.mjs',
      'node tooling/scripts/visual/check-clear-trigger.mjs',
      'node tooling/scripts/visual/check-coarse-target.mjs',
    ],
  },
  {
    id: 'overlay',
    label: '浮层',
    steps: [
      'node tooling/scripts/overlay/check-overlay-strategy.mjs',
      'node tooling/scripts/overlay/check-overlay-size.mjs',
      'node tooling/scripts/overlay/check-overlay-positioned.mjs',
      'node tooling/scripts/overlay/check-overlay-defaults.mjs',
      'node tooling/scripts/overlay/check-backdrop-variant.mjs',
      'node tooling/scripts/overlay/check-arrow-geometry.mjs',
      'node tooling/scripts/overlay/check-portal-target.mjs',
      'node tooling/scripts/overlay/check-scrollbar-hosts.mjs',
    ],
  },
  {
    id: 'motion',
    label: '动效',
    steps: [
      'node tooling/scripts/motion/check-keyframe-refs.mjs',
      'node tooling/scripts/motion/check-keyframe-registry.mjs',
      'node tooling/scripts/motion/check-infinite-motion.mjs',
      'node tooling/scripts/motion/check-motion-primitives.mjs',
      'node tooling/scripts/motion/check-motion-easing.mjs',
      'node tooling/scripts/motion/check-motion-role.mjs',
      'node tooling/scripts/motion/check-will-change.mjs',
      'node tooling/scripts/motion/check-motion-amplitude.mjs',
      'node tooling/scripts/motion/check-motion-source.mjs',
      'node tooling/scripts/motion/check-reduced-motion-channel.mjs',
      'node tooling/scripts/motion/check-motion-js-timing.mjs',
      'node tooling/scripts/motion/check-presence-pair.mjs',
      'node tooling/scripts/motion/check-motion-coverage.mjs',
    ],
  },
  {
    id: 'a11y',
    label: '焦点、键盘与 ARIA',
    steps: [
      'node tooling/scripts/a11y/check-focus-ring.mjs',
      'node tooling/scripts/a11y/check-focus-ring-surface.mjs',
      'node tooling/scripts/a11y/check-focus-outline-reset.mjs',
      'node tooling/scripts/a11y/check-key-repeat.mjs',
      'node tooling/scripts/a11y/check-keyboard-suites.mjs',
      'node tooling/scripts/a11y/check-focus-report.mjs',
      'node tooling/scripts/a11y/check-focus-restore.mjs',
      'node tooling/scripts/a11y/check-aria-shapes.mjs',
    ],
  },
  {
    id: 'adapter',
    label: '部件契约与三端接线',
    steps: [
      'node tooling/scripts/adapter/check-adapter-inline-style.mjs',
      'node tooling/scripts/adapter/check-vue-prop-defaults.mjs',
      'node tooling/scripts/adapter/check-computed-parity.mjs',
      'node tooling/scripts/adapter/check-part-wiring.mjs',
      'node tooling/scripts/adapter/check-field-wiring.mjs',
      'node tooling/scripts/adapter/check-form-reset.mjs',
      'node tooling/scripts/adapter/check-slot-types.mjs',
      'node tooling/scripts/adapter/check-translations-slots.mjs',
      'node tooling/scripts/adapter/check-config-wiring.mjs',
      'node tooling/scripts/adapter/check-dir-exposed.mjs',
      'node tooling/scripts/adapter/check-react-coverage.mjs',
      'node tooling/scripts/adapter/check-native-events.mjs',
      'node tooling/scripts/adapter/check-part-vocabulary.mjs',
      'node tooling/scripts/adapter/check-state-vocabulary.mjs',
      'node tooling/scripts/adapter/check-dead-state-attr.mjs',
      'node tooling/scripts/adapter/check-cem-coverage.mjs',
      'node tooling/scripts/adapter/check-read-ports.mjs',
      'node scripts/new-component.mjs --verify',
    ],
  },
  {
    id: 'docs',
    label: '文档与示例',
    steps: [
      'node tooling/scripts/docs/check-demo-frameworks.mjs',
      'node tooling/scripts/docs/check-demo-tokens.mjs',
      'node tooling/scripts/docs/check-demo-motion.mjs',
      'node tooling/scripts/docs/check-doc-design-language.mjs',
      'node tooling/scripts/docs/check-doc-media-placeholders.mjs',
      'node tooling/scripts/docs/check-demo-imports.mjs',
      'node tooling/scripts/docs/check-demo-count.mjs',
      'node tooling/scripts/docs/check-catalog-preview.mjs',
      'node tooling/scripts/docs/check-demo-scroll.mjs',
      'node tooling/scripts/docs/check-doc-imports.mjs',
      'node tooling/scripts/docs/check-doc-numbers.mjs',
    ],
  },
  {
    id: 'repo',
    label: '仓库工程与发版',
    steps: [
      'node tooling/scripts/repo/check-browser-config.mjs',
      'node tooling/scripts/repo/check-typecheck-scope.mjs',
      'node tooling/scripts/repo/check-typecheck-coverage.mjs',
      'node tooling/scripts/repo/check-pr-templates.mjs',
      'node tooling/scripts/repo/check-commit-scopes.mjs',
      'node tooling/scripts/repo/check-release-tag.mjs',
      'node tooling/scripts/repo/check-changeset-required.mjs',
      'node tooling/scripts/repo/check-changeset-packages.mjs',
      'node tooling/scripts/repo/check-visual-baseline-env.mjs',
      'node tooling/scripts/repo/check-visual-performance-budget.mjs',
      'node tooling/scripts/repo/check-file-headers.mjs',
      'node tooling/scripts/repo/check-wiring.mjs',
    ],
  },
]
