export { gradientTextAnatomy } from './gradient-text.anatomy'
export { connectGradientText } from './gradient-text.connect'
export { gradientTextKeyboard } from './gradient-text.keyboard'
export { gradientTextMeta } from './gradient-text.meta'
export type { GradientTextApi, GradientTextDirection, GradientTextProps, GradientTextTranslations } from './gradient-text.types'
