packages:
  - packages/*
  - internal/*
  - playground
catalog:
  "@types/node": 22.13.17
  "@vitejs/plugin-vue": 5.2.3
  "@vitejs/plugin-vue-jsx": 4.1.2
  "@types/glob": 8.1.0
  "@changesets/changelog-github": 0.5.1
  "@changesets/cli": 2.28.1
  unbuild: 3.5.0
  cross-env: 7.0.3
  eslint: 9.23.0
  eslint-config-prettier: 10.1.1
  eslint-plugin-prettier: 5.2.5
  eslint-plugin-vue: 10.0.0
  prettier: 3.5.3
  rollup: 4.38.0
  sass: 1.86.1
  rollup-plugin-scss: 4.0.1
  sass-lint: 1.13.1
  stylelint: 16.17.0
  tsx: 4.19.3
  typescript: 5.8.2
  vue: 3.5.13
  vite: 6.2.4
  turbo: 2.4.4
  vite-plugin-dts: 4.5.3
  vite-plugin-vue-devtools: 7.7.2
  vue-tsc: 2.2.8
  glob: 11.0.1
  pinia: 3.0.1
  vue-router: 4.5.0
