packages:
  - packages/*
  - internal/*
  - playground
catalog:
  "@types/node": 22.14.1
  "@vitejs/plugin-vue": 5.2.3
  "@vitejs/plugin-vue-jsx": 4.1.2
  "@types/glob": 8.1.0
  "@changesets/changelog-github": 0.5.1
  "@changesets/cli": 2.29.2
  unbuild: 3.5.0
  cross-env: 7.0.3
  eslint: 9.25.1
  eslint-config-prettier: 10.1.2
  eslint-plugin-prettier: 5.2.6
  eslint-plugin-vue: 10.0.0
  prettier: 3.5.3
  rollup: 4.40.0
  sass: 1.87.0
  rollup-plugin-scss: 4.0.1
  sass-lint: 1.13.1
  stylelint: 16.19.0
  tsx: 4.19.3
  typescript: 5.8.3
  vue: 3.5.13
  vite: 6.3.3
  turbo: 2.5.1
  vite-plugin-dts: 4.5.3
  vite-plugin-vue-devtools: 7.7.5
  vue-tsc: 2.2.10
  glob: 11.0.2
  pinia: 3.0.2
  vue-router: 4.5.0
